### ISSUE TITLE
Add examples to mobility.yaml

### ISSUE THREAD

**Issue by ravi-prakash-v** [beckn/mobility#10]
The current mobility specification does not have any examples added to it leading to varied interpretations and implementation of mobility use cases on beckn. The current implementors of beckn protocol in the domain of mobility must add their examples to the spec so that they can be reviewed by the mobility working group and published.

Committers are requested to raise PRs to the `draft` branch of the specification.

**Comment by core-wg-admin** [comment]
Added examples for search, select, init, confirm, and on_search
